FROM node:18

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV TRANSMISSION_HOST 
ENV TRANSMISSION_PORT 
ENV TRANSMISSION_USERNAME 
ENV TRANSMISSION_PASSWORD
EXPOSE 3000
CMD npm run dev