FROM node:18

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV TRANSMISSION_HOST=192.168.1.111
ENV TRANSMISSION_PORT=9091
ENV TRANSMISSION_USERNAME=admin
ENV TRANSMISSION_PASSWORD=admin
EXPOSE 3000
CMD npm run dev